#!/bin/sh
#PBS -N job5
#PBS -S /bin/bash
#PBS -j oe
#PBS -W umask=022
#PBS -l walltime=00:30:00
#PBS -l ncpus=1
#PBS -l mem=50mb

module load intel
module load mpt
export PATH=/ptmp/bwhopkin/molpro_mpt/2012/molprop_2012_1_Linux_x86_64_i8/bin:$PATH

export WORKDIR=$PBS_O_WORKDIR
export TMPDIR=/tmp/$USER/$PBS_JOBID
cd $WORKDIR
mkdir -p $TMPDIR

date
mpiexec molpro.exe input5.com input5.out
date

rm -rf $TMPDIR